import { type NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest, { params }: { params: { candidateId: string } }) {
  try {
    const { candidateId } = params

    // Create a proper resume content
    const resumeContent = generateResumeContent(candidateId)

    // Create response with proper headers for DOCX download
    const response = new NextResponse(resumeContent, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${candidateId}_resume.docx"`,
        "Cache-Control": "no-cache",
      },
    })

    return response
  } catch (error) {
    console.error("Resume download error:", error)
    return NextResponse.json({ error: "Failed to generate resume" }, { status: 500 })
  }
}

function generateResumeContent(candidateId: string): Buffer {
  // Create a simple text-based resume content
  // In a real application, you would use a library like docx to create proper DOCX files
  const resumeText = `
RESUME - ${candidateId.toUpperCase()}

CONTACT INFORMATION
Email: info@arcadianetwork.io
Phone: +49 178 603 2 432
Location: Munich, Germany

PROFESSIONAL SUMMARY
Experienced software professional with expertise in modern technologies and best practices.
Strong background in software development, problem-solving, and team collaboration.

TECHNICAL SKILLS
- Programming Languages: JavaScript, TypeScript, Python
- Frameworks: React, Node.js, Next.js
- Databases: PostgreSQL, MongoDB
- Cloud: AWS, GCP, Azure
- Tools: Docker, Kubernetes, Git

EXPERIENCE
Senior Software Engineer (2020 - Present)
- Led development of scalable web applications
- Mentored junior developers
- Implemented best practices and code reviews

Software Engineer (2018 - 2020)
- Developed full-stack applications
- Collaborated with cross-functional teams
- Participated in agile development processes

EDUCATION
Bachelor's Degree in Computer Science
Technical University of Munich

CERTIFICATIONS
- AWS Certified Solutions Architect
- Google Cloud Professional Developer
- Certified Kubernetes Administrator

---
Generated by Arcadia Network
Munich, Germany
info@arcadianetwork.io
+49 178 603 2 432
`

  // Convert text to buffer (in a real app, you'd create a proper DOCX file)
  return Buffer.from(resumeText, "utf-8")
}
